### ISSUE TITLE
Add Pokémon type along with attack and defense points in a <p> tag, consume from the API the pokémon type along with the attack and defense points. 

### ISSUE THREAD

**Issue by dnewbie25** [dnewbie25/dani-camp#4]

**Comment by dnewbie25** [comment]
You would like to try this endpoint  [https://pokeapi.co/api/v2/pokemon/](https://pokeapi.co/api/v2/pokemon/ditto)

The thing you should look for are the keys "type" and "stats"

**Comment by DRojasLey** [comment]
## Completed feature 
Currently under "feature/type-atck-def-visualization"

Features included:
* Stats are now dynamically shown for the corresponding Pokemon.
* Stats colors are updated depending on the winner.
* Match is now calculated on real attack stats of each Pokemon.
